#pragma once

#include "NativeGameplayTags.h"

namespace FragmentTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GridFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IconFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StackableFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumableFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EquipmentFragment)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemNameFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PrimaryStatFragment)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemTypeFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FlavorTextFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SellValueFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RequiredLevelFragment)

	namespace StatMod
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_1)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_2)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_3)
	}
}
